#!/usr/local/bin/python

#-----------------------------------------------------------------------------
# Copyright (c) 2014, John W. O'Brien
# All rights reserved.
#
# Distributed under the terms of the BSD Simplified License.
#
# The full license is in the LICENSE file, distributed with this software.
#-----------------------------------------------------------------------------

if __name__ == '__main__':
    pass
